### ISSUE TITLE
Krypton Testing Issues

### ISSUE THREAD

**Issue by siuside** [kodi-addons/plugin.video.espn_3#1]
Did you want to start a new branch for this? I wanted to see if the TLS issue happens with updated gnutls in Krypton (for which I have some more information just FYI in #26 )

- I had to import urllib2 to get inside the addon

- The main menu doesn't populate the premiums only the espn3 events and that too not inside a folder.
Authentication is not working and debug isn't providing much information

- http://pastebin.com/PY7kg05c

**Comment by awaters1** [comment]
I tried alpha 2 and things seemed to be working, I'll keep this open though until the beta/rc comes out to test everything.

**Comment by awaters1** [comment]
Beta 2 works well.
