### ISSUE TITLE
SNI Missing Error

### ISSUE THREAD

**Issue by siuside** [kodi-addons/plugin.video.espn_3#16]
Getting this lately in Windows 10 / Kodi 16.0

http://pastebin.com/pJrRR19e

Don't think I had seen this before. Please let me know if you need any additional details captured.. I have tried to disable SSL but that didn't work.

**Comment by awaters1** [comment]
That is a weird issue, I will have to start up my Windows 10 VM to see if I can reproduce it.

**Comment by siuside** [comment]
I was able to narrow it down and eventually fix the issue. This is not an addon issue, but to have a datapoint in case someone else runs into it. 

I was subscribed to a DNS service which expired sometime in the last week or so. I used it primarily to get around blackouts but see no reason to continue with the services. I had to remove the DNS servers that came with the service from network configuration of the PC and restart the network service for it to take effect.

So essentially SNI error = Rogue DNS servers in network = User Error.

Please feel free to close it
