### ISSUE TITLE
Addon fails to open

### ISSUE THREAD

**Issue by InsanesTheName** [kodi-addons/plugin.video.espn_3#21]
Recently, the addon hasn't been working at all. It appears to be having trouble accessing a URL:
```
09:15:05.693 T:5268   DEBUG: SSL certificate failure HTTPConnectionPool(host='www.secure.espn.com', port=80): Max retries exceeded with url: /watchespn/feeds/startup?action=live&channel=accextra,espn3,espn1,espn2,espnu,goalline,buzzerbeater,espnews,espndeportes,sec,secplus,longhorn (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x291523B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
```

A full debug log paste can be found [here](https://paste.kodi.tv/ibacafalem.kodi). 

It looks to be platform-independent (I've tried on Windows, OSMC, and Ubuntu). I'm using v2.9.25.

**Comment by awaters1** [comment]
Hello, are you able to visit
https://secure.espn.com/watchespn/feeds/startup?action=live&channel=accextra,espn3,espn1,espn2,espnu,goalline,buzzerbeater,espnews,espndeportes,sec,secplus,longhorn
In a web browser on the same machine as Kodi? The causes of the error is an SSL certificate failure, which shouldn't really happen, as a workaround you can disable SSL verification checks within the addon settings.

**Comment by InsanesTheName** [comment]
Hmm I had tried that earlier (even with SSL disabled) and it wasn't resolving. It does resolve now and the addon seems to be working again. 

Thanks for your quick response!
