### ISSUE TITLE
ACCNetwork is not available as a channel

### ISSUE THREAD

**Issue by lionsnob** [kodi-addons/plugin.video.espn_3#23]
I've attached a tcpdump of me logging in with my provider and selecting an ACCNetwork video. The network is brand new (as of 8/22 I believe). Confusingly, there are also sporting events under the ACCNetwork Xtra channel, which acts more like ESPN3 than a linear channel.

[cablePrividerLogin.pcap.txt](https://github.com/kodi-addons/plugin.video.espn_3/files/3539278/cablePrividerLogin.pcap.txt)

**Comment by awaters1** [comment]
Can you try out 2.9.31 within https://github.com/kodi-addons/repo.kodi-addons ? I hacked in support for ACCN.

**Comment by lionsnob** [comment]
It worked for me. Thank you.

**Comment by lionsnob** [comment]
At around 3pm EDT, the add-on started throwing an error to check the log and is not working. Unfortunately I had to leave for the Michigan game at that time. Coincidentally, this is the time that ESPN Goalline started broadcasting. If the behavior is continuing when I get home I’ll capture a log.

**Comment by awaters1** [comment]
I'll keep an eye out, when does ESPN goalline show up usually?

**Comment by lionsnob** [comment]
Saturday’s from 3p to 11p. I’ll check on Saturday too.

**Comment by lionsnob** [comment]
It seems to be working now. Did you update the add on?

**Comment by awaters1** [comment]
I didn't, I think I found the issue, some shows for the ACC network were missing thumbnails, 2.10.0 should fix the issue.

**Comment by lionsnob** [comment]
Confirmed that it’s working this morning. Shall I close this issue?

**Comment by awaters1** [comment]
Good to hear
