### ISSUE TITLE
ESPN GoalLine will not launch in ESPN3 addon

### ISSUE THREAD

**Issue by lionsnob** [kodi-addons/plugin.video.espn_3#25]
Shows in the list as "Unknown nwtwork n25 ESPN Goal Line". Log attached.
[kodi.log](https://github.com/kodi-addons/plugin.video.espn_3/files/3587183/kodi.log)

**Comment by awaters1** [comment]
I released 2.10.0 that should fix this as well

**Comment by lionsnob** [comment]
Thanks! I’ll confirm Saturday as Goal Line is only active from 3-11p on Saturdays.

**Comment by lionsnob** [comment]
It works! Thank you for addressing this!

**Comment by awaters1** [comment]
Sounds good, thank for testing.
