### ISSUE TITLE
Issue with none subscribed channels

### ISSUE THREAD

**Issue by usphil** [kodi-addons/plugin.video.espn_3#29]
Hi, 

Thanks a lot for this update with ESPN+. 

It works great but I have a problem with my Sling subscription. Sling doesn't have ESPN Deportes, ACCN and Longhorn on their network. So event I disabled these channels from the user settings, they were still in the live events list. If I forget to click these links, my device would be unauthorized, and I had to signup again. That happens many time. So will it be fixed in the next update?

Thank you!

Phil

**Comment by t43pasdf** [comment]
Sure will, I'll see if I can make it work better.

**Comment by t43pasdf** [comment]
See if 3.0.1 works better for you, https://github.com/kodi-addons/repo.kodi-addons/blob/master/plugin.video.espn_3/plugin.video.espn_3-3.0.1.zip

**Comment by usphil** [comment]
It's better, no Deportes and ACC, but still LHN. Please take a look. 

Thank you ssssssssssssso much!

**Comment by t43pasdf** [comment]
Sounds good, I corrected the issue with LHN in 3.0.2 - https://github.com/kodi-addons/repo.kodi-addons/blob/master/plugin.video.espn_3/plugin.video.espn_3-3.0.2.zip

**Comment by usphil** [comment]
Perfect! for me now. Greatly appreciated.

**Comment by t43pasdf** [comment]
Cool
