### ISSUE TITLE
update log level

### ISSUE THREAD

**Issue by locomot1f** [kodi-addons/plugin.video.espn_3#5]
and this ...
In plugin.video.espn_3/addon.py:

> +
> +
> +    # see aHR0cDovL2FwaS1hcHAuZXNwbi5jb20vdjEvd2F0Y2gvY2xpZW50cy93YXRjaGVzcG4tdHZvcw== for details
> +    # see aHR0cDovL2VzcG4uZ28uY29tL3dhdGNoZXNwbi9hcHBsZXR2L2ZlYXR1cmVk for details
> +    start_session_url = args.get(SESSION_URL)[0]
> +    params = urllib.urlencode({'partner':'watchespn',
> +                               'playbackScenario':'HTTP_CLOUD_HIGH',
> +                               'platform':'chromecast_uplynk',
> +                               'token':media_token,
> +                               'tokenType':token_type,
> +                               'resource':base64.b64encode(resource),
> +                               'v': '2.0.0'
> +                               })
> +    start_session_url += '&' + params
> +
> +    xbmc.log('ESPN3: start_session_url: ' + start_session_url, LOG_LEVEL)

I think you should be using DEBUG_LEVEL rather than LOG_LEVEL

**Comment by awaters1** [comment]
Should be fixed
