### ISSUE TITLE
use listItem.setArt and set mediatype

### ISSUE THREAD

**Issue by locomot1f** [kodi-addons/plugin.video.espn_3#6]
In plugin.video.espn_3/resources/lib/addon_util.py:

> +    video_streaminfo = dict()
> +    liz.addStreamInfo('video', video_streaminfo)
> +    ok = xbmcplugin.addDirectoryItem(handle=pluginhandle, url=u, listitem=liz)
> +    return ok
> +
> +
> +def addDir(name, url, iconimage, fanart=None, infoLabels=None):
> +    u = sys.argv[0] + '?' + urllib.urlencode(url)
> +    xbmc.log(TAG + 'Made url to %s' % u, LOG_LEVEL)
> +    liz = xbmcgui.ListItem(name, iconImage="DefaultFolder.png", thumbnailImage=iconimage)
> +    if infoLabels is None:
> +        infoLabels={"Title": name}
> +    liz.setInfo(type="Video", infoLabels=infoLabels)
> +    if fanart is None:
> +        fanart=defaultfanart
> +    liz.setProperty('fanart_image',fanart)

In Isengard and above, you should use listItem.setArt() in place of the setProperty for fanart, as well as the icon and thumbnail in the listItem init,. You should also be setting the appropriate 'mediatype' infoLabel for the item.

**Comment by locomot1f** [comment]
i think i made the correct changes for this. 
needs a second eye.

**Comment by awaters1** [comment]
Do you know what they mean by mediatype infoLabel?

**Comment by awaters1** [comment]
Should be fixed
